version: "3"
services:
    status-client:
        image: darknightlab/status-client:main
        # build: ./
        container_name: status-client
        restart: always
        network_mode: bridge
        command: 
            - --dsn
            - wss://username:password@status.mydomain.com

